import { useLang } from '../contexts/LanguageContext.jsx'
import { moduleCopyKn, sectionTitleKn } from '../data/translations_kn.js'

const en = {
  appTitle: 'Flutter & Dart Tutorial',
  heroEyebrow: 'Cross-platform mobile mastery',
  heroTitlePrefix: 'Flutter & Dart Tutorial by',
  heroDescription:
    'Track every topic, project, and quiz across the full 7-module curriculum - from Dart syntax to publishing apps on Google Play and the App Store.',
  overallProgress: 'Overall progress',
  moduleProgress: 'Module progress',
  dashboard: 'Dashboard',
  modules: 'Modules',
  topics: 'Topics',
  projects: 'Projects',
  quiz: 'Quiz',
  notes: 'Notes',
  hours: 'Hours',
  progress: 'Progress',
  export: 'Export',
  import: 'Import',
  resetAllProgress: 'Reset all progress',
  signOut: 'Sign out',
  learner: 'Learner',
  backToDashboard: 'Back to dashboard',
  searchPlaceholder: 'Search topics - title or content...',
  noMatchingTopics: 'No matching topics.',
  result: 'result',
  results: 'results',
  navigate: 'navigate',
  open: 'open',
  close: 'close',
  clearSearch: 'Clear search',
  resetConfirm:
    'Reset ALL progress? This clears completed topics, notes, and quiz scores.',
  importConfirm: 'Import this backup? Your current progress will be replaced.',
  importError: 'Could not import: ',
  invalidJson: 'invalid JSON file.',
  loading: 'Loading...',
  syncingProgress: 'Syncing your progress...',
  footerSync: 'Progress syncs to your Google account - export anytime for a manual backup.',
  builtWith: 'Built with',
  inKundapura: 'in Kundapura',
  footerCredit: '',
  notesFor: 'Notes for',
  notesPlaceholder:
    'Jot down anything: questions, links, snippets, study reminders...',
  notesSaved: 'Saved automatically to your browser.',
  moduleQuiz: 'Module Quiz',
  pickBestAnswer: 'Pick the best answer.',
  lastAttempt: 'Last attempt',
  submitAnswers: 'Submit answers',
  perfectScore: 'Perfect - you nailed every question.',
  solidScore: 'Solid work - most concepts locked in.',
  reviewScore: 'Review the topics above and try again.',
  retake: 'Retake',
  tools: 'Tools',
  buildBlueprintAvailable: 'Build blueprint available',
  hide: 'Hide',
  functionalRequirements: 'Functional requirements',
  technicalImplementation: 'Technical implementation',
  claudePrompts: 'Claude Code prompts (copy-paste in order)',
  copy: 'Copy',
  copied: 'Copied',
  copyAll: 'Copy all',
  finalDeliverable: 'Final deliverable',
  promptHint:
    'Paste each prompt into Claude Code in order. Wait for it to finish before sending the next - each step builds on the last.',
  exportTitle: 'Download a JSON backup of your progress',
  importTitle: 'Restore progress from a JSON backup',
  loginEyebrow: 'Sign in to track your progress',
  loginTitle: 'Flutter & Dart Tutorial',
  loginSubtitle:
    'Sign in with Google to save your topics, notes, and quiz results across devices - kori rotti for your codebase.',
  continueWithGoogle: 'Continue with Google',
  signingIn: 'Signing you in...',
  loginError: 'Could not sign in: ',
  loginPrivacy:
    'We only use your Google profile (name, email, photo) to label your progress. Nothing else.',
  loadingAuth: 'Checking sign-in...',
  // Hero login page
  heroPill: 'Structured · Hands-on · Coast-to-cloud',
  heroH1Prefix: 'Master',
  heroH1Highlight: 'Flutter & Dart',
  heroH1Suffix: 'from scratch',
  heroLead:
    'A structured, hands-on curriculum from Dart fundamentals to publishing on Google Play and the App Store.',
  heroLeadStrong: 'No paywalls. Ever.',
  badgeFreeLine1: 'COMPLETELY',
  badgeFreeLine2: 'FREE',
  badgeFreeLine3: 'COURSE',
  featTopicsTitle: 'Topics',
  featTopicsBody: 'Dart syntax to publishing - structured step-by-step.',
  featCurriculumTitle: 'Mobile-First Curriculum',
  featCurriculumBody: 'Widgets, state, networking, navigation & deployment.',
  featQuizzesTitle: 'Quizzes & Projects',
  featQuizzesBody: 'Test understanding with real-world challenges.',
  featCloudTitle: 'Cloud Progress',
  featCloudBody: 'Synced across all your devices automatically.',
  featFreeTitle: 'Fast & Free',
  featFreeBody: 'No paywalls - learn at your own pace.',
  loginWelcome: 'Welcome back',
  loginCardSubtitle:
    'Sign in to sync your progress across all your devices and continue where you left off.',
  statTopicsLabel: 'Topics',
  statFreeLabel: 'Free',
  statAccessLabel: 'Access',
  statAccessValue: 'Unlimited',
  loginTrust1: 'Auto-synced across all your devices',
  loginTrust2: 'No paywalls — fully open access',
  loginTrust3: 'Privacy-first — only profile basics',
  loginCardFootnote: 'Progress stored securely in Firebase · Never shared',
}

const kn = {
  appTitle: 'Flutter & Dart Tutorial',
  heroEyebrow: 'Cross-platform mobile mastery',
  heroTitlePrefix: 'Flutter & Dart Tutorial by',
  heroDescription:
    'Dart syntax ಇಂದ app publish ಮಾಡುವವರೆಗೆ topics, projects ಮತ್ತು quiz progress easy ಆಗಿ track ಮಾಡಿ.',
  overallProgress: 'Total progress',
  moduleProgress: 'Module progress',
  dashboard: 'Dashboard',
  modules: 'Modules',
  topics: 'Topics',
  projects: 'Projects',
  quiz: 'Quiz',
  notes: 'Notes',
  hours: 'Hours',
  progress: 'Progress',
  export: 'Export',
  import: 'Import',
  resetAllProgress: 'ಎಲ್ಲ progress reset ಮಾಡಿ',
  signOut: 'Sign out',
  learner: 'Learner',
  backToDashboard: 'Dashboard ಗೆ back',
  searchPlaceholder: 'Topic search ಮಾಡಿ - title ಅಥವಾ content...',
  noMatchingTopics: 'Matching topics ಸಿಗಲಿಲ್ಲ.',
  result: 'result',
  results: 'results',
  navigate: 'navigate',
  open: 'open',
  close: 'close',
  clearSearch: 'Search clear ಮಾಡಿ',
  resetConfirm:
    'ಎಲ್ಲ progress reset ಮಾಡಬೇಕಾ? Completed topics, notes ಮತ್ತು quiz scores clear ಆಗುತ್ತವೆ.',
  importConfirm: 'ಈ backup import ಮಾಡಬೇಕಾ? ಈಗಿನ progress replace ಆಗುತ್ತದೆ.',
  importError: 'Import ಆಗಲಿಲ್ಲ: ',
  invalidJson: 'invalid JSON file.',
  loading: 'Loading...',
  syncingProgress: 'ನಿಮ್ಮ progress sync ಆಗುತ್ತಿದೆ...',
  footerSync: 'Progress ನಿಮ್ಮ Google account ಗೆ sync ಆಗುತ್ತದೆ - backup ಬೇಕಾದಾಗ export ಮಾಡಿ.',
  builtWith: 'Built with',
  inKundapura: 'Kundapura ಯಲ್ಲಿ',
  footerCredit: 'ಕುಂದಾಪುರದಲ್ಲಿ ತಂತ್ರಜ್ಞಾನಿ ಅವ್ರು ಪ್ರೀತಿಯಿಂದ ಅಭಿವೃದ್ಧಿಪಡಿಸಿದ ಅಪ್ಲಿಕೇಶನ್',
  notesFor: 'Notes for',
  notesPlaceholder:
    'Questions, links, snippets, reminders ಏನಾದರೂ ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
  notesSaved: 'Browser ನಲ್ಲಿ automatic save ಆಗುತ್ತದೆ.',
  moduleQuiz: 'Module Quiz',
  pickBestAnswer: 'Best answer select ಮಾಡಿ.',
  lastAttempt: 'Last attempt',
  submitAnswers: 'Answers submit ಮಾಡಿ',
  perfectScore: 'Perfect - ಎಲ್ಲ questions nailed.',
  solidScore: 'ಚೆನ್ನಾಗಿದೆ - most concepts lock ಆಗಿವೆ.',
  reviewScore: 'ಮೇಲಿನ topics review ಮಾಡಿ ಮತ್ತೆ try ಮಾಡಿ.',
  retake: 'Retake',
  tools: 'Tools',
  buildBlueprintAvailable: 'Build blueprint ಇದೆ',
  hide: 'Hide',
  functionalRequirements: 'Functional requirements',
  technicalImplementation: 'Technical implementation',
  claudePrompts: 'Claude Code prompts (ಕ್ರಮವಾಗಿ copy-paste ಮಾಡಿ)',
  copy: 'Copy',
  copied: 'Copied',
  copyAll: 'ಎಲ್ಲ copy ಮಾಡಿ',
  finalDeliverable: 'Final deliverable',
  promptHint:
    'ಪ್ರತಿ prompt ಅನ್ನು Claude Code ಗೆ order ನಲ್ಲಿ paste ಮಾಡಿ. ಒಂದು finish ಆದ ಮೇಲೆ next prompt ಕಳುಹಿಸಿ.',
  exportTitle: 'Progress JSON backup download ಮಾಡಿ',
  importTitle: 'JSON backup ನಿಂದ progress restore ಮಾಡಿ',
  loginEyebrow: 'Progress track ಮಾಡಲು sign in ಮಾಡಿ',
  loginTitle: 'Flutter & Dart Tutorial',
  loginSubtitle:
    'Sign in ಮಾಡಿ ನಿಮ್ಮ topics, notes ಮತ್ತು quiz results ಅನ್ನು ಎಲ್ಲಾ devices ನಲ್ಲಿ save ಮಾಡಿಕೊಳ್ಳಿ.',
  continueWithGoogle: 'Continue with Google',
  signingIn: 'Sign in ಆಗುತ್ತಿದೆ...',
  loginError: 'Sign in ಆಗಲಿಲ್ಲ: ',
  loginPrivacy:
    'ನಿಮ್ಮ progress label ಮಾಡಲು Google profile (name, email, photo) ಮಾತ್ರ use ಮಾಡುತ್ತೇವೆ. ಬೇರೆ ಏನೂ ಇಲ್ಲ.',
  loadingAuth: 'Sign-in check ಆಗುತ್ತಿದೆ...',
  // Hero login page
  heroPill: 'Structured · Hands-on · Kannada-friendly',
  heroH1Prefix: 'Master',
  heroH1Highlight: 'Flutter & Dart',
  heroH1Suffix: 'from scratch',
  heroLead:
    'Learn Dart basics ಇಂದ app publish ಮಾಡುವವರೆಗೆ, practical examples ಮತ್ತು step-by-step lessons ಜೊತೆ.',
  heroLeadStrong: 'Paywall ಇಲ್ಲ. Full course free.',
  badgeFreeLine1: 'FULL',
  badgeFreeLine2: 'FREE',
  badgeFreeLine3: 'COURSE',
  featTopicsTitle: 'Topics',
  featTopicsBody: 'Dart syntax ಇಂದ app publishing ವರೆಗೆ, step-by-step ಆಗಿ.',
  featCurriculumTitle: 'Mobile-First Curriculum',
  featCurriculumBody: 'Widgets, state, networking, navigation & deployment ಎಲ್ಲವೂ ಒಂದೇ flow ನಲ್ಲಿ.',
  featQuizzesTitle: 'Quizzes & Projects',
  featQuizzesBody: 'Real-world tasks ಮೂಲಕ ನಿಮ್ಮ understanding test ಮಾಡಿ.',
  featCloudTitle: 'Cloud Progress',
  featCloudBody: 'Progress ಎಲ್ಲಾ devices ನಲ್ಲಿ automatic sync ಆಗುತ್ತದೆ.',
  featFreeTitle: 'Fast & Free',
  featFreeBody: 'No paywalls. ನಿಮ್ಮ pace ನಲ್ಲಿ ಕಲಿಯಿರಿ.',
  featCoastTitle: 'Kundapura Flavour',
  featCoastBody: 'Kori rotti, Krishna Matha & Gangolli boat analogies.',
  loginWelcome: 'Welcome back',
  loginCardSubtitle:
    'Sign in ಮಾಡಿ progress sync ಮಾಡಿ, ನಂತರ ಎಲ್ಲಿ ಬಿಟ್ಟಿದ್ದೀರೋ ಅಲ್ಲಿಂದ continue ಮಾಡಿ.',
  statTopicsLabel: 'Topics',
  statFreeLabel: 'Free',
  statAccessLabel: 'Access',
  statAccessValue: 'Unlimited',
  loginTrust1: 'ಎಲ್ಲ devices ನಲ್ಲಿ auto-sync ಆಗುತ್ತದೆ',
  loginTrust2: 'Paywall ಇಲ್ಲ — ಸಂಪೂರ್ಣ open access',
  loginTrust3: 'Privacy-first — profile basics ಮಾತ್ರ',
  loginCardFootnote: 'Progress Firebase ನಲ್ಲಿ safe ಆಗಿ save ಆಗುತ್ತದೆ · share ಮಾಡುವುದಿಲ್ಲ',
}

export function useUiText() {
  const { lang } = useLang()
  return lang === 'kn' ? kn : en
}

export function useIsKannada() {
  const { lang } = useLang()
  return lang === 'kn'
}

export function getModuleCopy(module, isKannada) {
  if (!isKannada) return { title: module.title, description: module.description }
  const copy = moduleCopyKn[module.id] ?? {
    title: module.title,
    description: module.description,
  }
  return {
    title: module.title,
    description: copy.description,
  }
}

export function getSectionTitle(section, isKannada) {
  return section.title
}
